apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kong-gateway-metrics
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app.kubernetes.io/name: kong
      app.kubernetes.io/instance: my-kong
  endpoints:
    - port: status          # must match svc port name (from kubectl get svc)
      path: /metrics
      interval: 15s


