apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: key-auth
plugin: key-auth
config:
  key_names:
  - apikey # Expect the API key in a header named 'apikey'
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: rate-limiting-by-consumer
plugin: rate-limiting
config:
  hour: 5  
  limit_by: consumer
  policy: local
---
# Enable Prometheus metrics globally so /metrics is exposed
apiVersion: configuration.konghq.com/v1
kind: KongClusterPlugin
metadata:
  name: prometheus
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/plugins: prometheus
  labels:
    global: "true"
plugin: prometheus
config:
  status_code_metrics: true
  latency_metrics: true
  bandwidth_metrics: true
  upstream_health_metrics: true
  per_consumer: true
