apiVersion: v1
kind: Service
metadata:
  name: my-kong-kong-proxy
  namespace: default
  labels:
    app.kubernetes.io/name: kong
    app.kubernetes.io/instance: my-kong
    app.kubernetes.io/component: app
    app.kubernetes.io/managed-by: Helm
    helm.sh/chart: kong-2.51.0
    app.kubernetes.io/version: "3.9"
spec:
  type: LoadBalancer
  ports:
  - name: kong-proxy
    port: 80
    targetPort: 8000
    protocol: TCP
  - name: kong-proxy-tls
    port: 443
    targetPort: 8443
    protocol: TCP
  selector:
    app.kubernetes.io/name: kong
    app.kubernetes.io/component: app
    app.kubernetes.io/instance: my-kong


