apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-deployment
  labels:
    app: sentiment
    gpu: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sentiment
      gpu: "true"
  template:
    metadata:
      labels:
        app: sentiment
        gpu: "true"
    spec:
      automountServiceAccountToken: false
      nodeSelector:
        agentpool: gpunode1
        beta.kubernetes.io/arch: arm64
      containers:
      - name: sentiment
        image: avy1013/sentiment-app:latest
        imagePullPolicy: Always
        env:
        - name: HF_HOME
          value: "/cache/huggingface"
        - name: TRANSFORMERS_CACHE
          value: "/cache/huggingface/transformers"
        - name: XDG_CACHE_HOME
          value: "/cache"
        - name: PYTORCH_HOME
          value: "/cache/torch"
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: cache-volume
          mountPath: /cache
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          runAsNonRoot: true
          runAsUser: 1000
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
      volumes:
      - name: cache-volume
        emptyDir: {}
