apiVersion: apps/v1
kind: Deployment
metadata:
  name: generator-deployment
  labels:
    app: generator
    gpu: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: generator
      gpu: "true"
  template:
    metadata:
      labels:
        app: generator
        gpu: "true"
    spec:
      nodeSelector:
        agentpool: gpunode1
        beta.kubernetes.io/arch: arm64
      containers:
      - name: generator
        image: avy1013/generator-app:latest
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1Gi"