apiVersion: apps/v1
kind: Deployment
metadata:
  name: generator-deployment
  labels:
    app: generator
    gpu: "true"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: generator
      gpu: "true"
  template:
    metadata:
      labels:
        app: generator
        gpu: "true"
    spec:
      automountServiceAccountToken: false
      nodeSelector:
        agentpool: gpunode1
        beta.kubernetes.io/arch: arm64
      containers:
      - name: generator
        image: avy1013/generator-app:latest
        imagePullPolicy: Always
        env:
        - name: HF_HOME
          value: "/cache/huggingface"
        - name: TRANSFORMERS_CACHE
          value: "/cache/huggingface/transformers"
        - name: XDG_CACHE_HOME
          value: "/cache"
        - name: PYTORCH_HOME
          value: "/cache/torch"
        - name: TOKENIZERS_PARALLELISM
          value: "false"
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: cache-volume
          mountPath: /cache
        - name: tmp-volume
          mountPath: /tmp
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
        startupProbe:
          httpGet:
            path: /healthz
            port: 8000
          # Allow up to ~10 minutes for first successful start (model download/load)
          periodSeconds: 10
          failureThreshold: 60
          timeoutSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8000
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
      volumes:
      - name: cache-volume
        emptyDir: {}
      - name: tmp-volume
        emptyDir: {}