name: Build and Push Images

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
    	uses: actions/checkout@v4

    - name: Set up Docker Buildx
    	uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
    	uses: docker/login-action@v3
    	with:
    	  username: ${{ secrets.DOCKERHUB_USERNAME }}
    	  password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push generator-app
    	uses: docker/build-push-action@v5
    	with:
    	  context: ./apps/model_generator
    	  push: true
    	  tags: ${{ secrets.DOCKERHUB_USERNAME }}/generator-app:latest

    - name: Build and push sentiment-app
    	uses: docker/build-push-action@v5
    	with:
    	  context: ./apps/model_sentiment
    	  push: true
    	  tags: ${{ secrets.DOCKERHUB_USERNAME }}/sentiment-app:latest

    - name: Build and push credit-service
    	uses: docker/build-push-action@v5
    	with:
    	  context: ./apps/credit_service
    	  push: true
    	  tags: ${{ secrets.DOCKERHUB_USERNAME }}/credit-service:latest
