name: Build and Push Images

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: generator-app
            context: ./apps/model_generator
            tag: generator-app
          - name: sentiment-app
            context: ./apps/model_sentiment
            tag: sentiment-app
          - name: credit-service
            context: ./apps/credit_service
            tag: credit-service
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push ${{ matrix.name }}
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.tag }}:latest
